plugins {
    id "architectury-plugin" version "3.4.164"
    id "dev.architectury.loom" version "1.13-SNAPSHOT" apply false
}

architectury {
    minecraft = rootProject.minecraft_version
}

allprojects {
    apply plugin: "java"
    apply plugin: "architectury-plugin"
    apply plugin: "maven-publish"

    repositories {
        maven { url "https://maven.neoforged.net/releases/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.terraformersmc.com/" }
    }

    archivesBaseName = rootProject.archives_base_name
    version = rootProject.mod_version
    group = rootProject.maven_group

    tasks.withType(JavaCompile) {
        options.encoding = "UTF-8"
        options.release = 21
    }

    java {
        withSourcesJar()
    }
}

subprojects {
    apply plugin: "dev.architectury.loom"

    loom {
        silentMojangMappingsLicense()
        runs {
            client {
                client()
                name "Minecraft Client"
                runDir "run"
                programArgs "--username", "Dev1"
            }
            client2 {
                client()
                name "Minecraft Client 2"
                runDir "run_2"
                programArgs "--username", "Dev2"
            }
            server {
                server()
                name "Minecraft Server"
                runDir "run_server"
            }
        }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings loom.officialMojangMappings()
    }
}


