modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0"

[[mods]]
modId="bodycam"
version="1.0.0"
displayName="Bodycam"
authors="Clasher"
description="Erlaubt es den Spieler seine Freunde zu beobachten"

[[dependencies.bodycam]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bodycam]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
