modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0"

[[mods]]
modId="bodycam"
version="2.1.2A"
displayName="Bodycam"`r`nlogoFile="assets/bodycam/icon.png"
authors="Clasher"
description="Allows players to observe their friends"

[[dependencies.bodycam]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bodycam]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bodycam]]
    modId="architectury"
    type="required"
    versionRange="[13.0.8,)"
    ordering="NONE"
    side="BOTH"

